# Generated by Django 5.0 on 2024-01-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0004_alter_about_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
