# Generated by Django 5.0 on 2024-01-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0005_alter_about_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='role_description',
            field=models.TextField(),
        ),
    ]
