# Generated by Django 5.0 on 2024-01-03 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0006_about_description_alter_about_role_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='proficiency',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
