# Generated by Django 5.0 on 2024-01-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0007_skills_proficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=50)),
            ],
        ),
    ]
