# Generated by Django 5.0 on 2024-01-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0009_remove_interests_interest_interests_general_interest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interests',
            options={'verbose_name_plural': 'Interests'},
        ),
        migrations.RemoveField(
            model_name='interests',
            name='General_interest',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='Technical_interest',
        ),
        migrations.AddField(
            model_name='interests',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('general', 'General')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interests',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
