# Generated by Django 5.0 on 2024-01-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0011_education_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_year',
            field=models.CharField(max_length=20),
        ),
    ]
