# Generated by Django 5.0 on 2024-01-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0012_alter_experience_end_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='job_role',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='technical_skills',
            field=models.TextField(blank=True),
        ),
    ]
