# Generated by Django 5.0 on 2024-01-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0014_alter_experience_job_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=100)),
            ],
        ),
    ]
