# Generated by Django 5.0 on 2024-01-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0016_summary_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name': 'Summary', 'verbose_name_plural': 'Summaries'},
        ),
    ]
