# Generated by Django 5.0 on 2024-01-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0017_alter_summary_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.CharField(max_length=255),
        ),
    ]
