# Generated by Django 5.0 on 2024-01-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0018_alter_summary_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
