# Generated by Django 5.0 on 2024-01-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0019_education_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('app', 'App'), ('web', 'Web')], max_length=20, null=True),
        ),
    ]
