# Generated by Django 5.0 on 2024-01-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0021_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.FileField(upload_to='portfolio/'),
        ),
    ]
