# Generated by Django 5.0 on 2024-01-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0023_imagefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
    ]
