# Generated by Django 5.0 on 2024-01-05 17:33

import p_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0027_alter_imagefile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='image',
            field=models.ImageField(upload_to=p_app.models.ImageFile._get_upload_path),
        ),
    ]
