# Generated by Django 5.0 on 2024-01-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0028_alter_imagefile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
